/*
 * This source file was generated by the Gradle 'init' task
 */
package org.project;

import org.project.data.JsonRepository;
import org.project.data.OsData;
import org.project.frames.Entry;
import org.project.frames.Home;
import org.project.models.*;
import org.project.services.*;

import javax.swing.*;
import java.io.File;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        String filePath=OsData.getUserDataPath ("users.json");
        File file=new File(filePath);
        if(!file.exists()){
            file.createNewFile();
        }
        UserService userService=new UserService(new JsonRepository<>(filePath, User[].class));
//----------------------------------------------------------------------------------------------------
        String orderFilePath=OsData.getUserDataPath("orders.json");
        File orderFile=new File(orderFilePath);
        if(!orderFile.exists()){
            orderFile.createNewFile();
        }
        OrderService orderService=new OrderService(new JsonRepository<>(filePath, Order[].class));
//----------------------------------------------------------------------------------------------------
        String receiverFilePath=OsData.getUserDataPath("receivers.json");
        File receiverFile=new File(receiverFilePath);
        if(!receiverFile.exists()){
            receiverFile.createNewFile();
        }
        ReceiverService receiverService=new ReceiverService(new JsonRepository<>(filePath, Receiver[].class));
//----------------------------------------------------------------------------------------------------
        String storeFilePath=OsData.getUserDataPath("stores.json");
        File storeFile =new File(storeFilePath);
        if(!storeFile.exists()){
            storeFile.createNewFile();
        }
        StoreService storeService=new StoreService(new JsonRepository<>(filePath, Store[].class));
//----------------------------------------------------------------------------------------------------
        String productFilePath=OsData.getUserDataPath("products.json");
        File productFile=new File(productFilePath);
        if(!productFile.exists()){
            productFile.createNewFile();
        }
        ProductService productService=new ProductService(new JsonRepository<>(filePath, Product[].class));
//----------------------------------------------------------------------------------------------------
        String cargoFilePath=OsData.getUserDataPath("cargos.json");
        File cargoFile=new File(cargoFilePath);
        if(!cargoFile.exists()){
            cargoFile.createNewFile();
        }
        CargoService cargoService=new CargoService(new JsonRepository<>(cargoFilePath, Cargo[].class));

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Entry();
                //new Home();
            }
        });

    }
}

/*
        UserService userService=new UserService(new JsonRepository<>(filePath, User[].class));
        String filePathUser=OsData.getUserDataPath("users.json");
        File userFile=new File(filePathUser);
        if(!userFile.exists()){
            userFile.createNewFile();
        }
        OrderService orderService=new OrderService(new JsonRepository<>(filePath, Order[].class));
        String filePathOrder=OsData.getUserDataPath("orders.json");
        File orderFile=new File(filePathOrder);
        if(!orderFile.exists()){
            orderFile.createNewFile();
        }
        StoreService storeService =new StoreService(new JsonRepository<>(filePath, Store[].class));
        String filePath=OsData.getUserDataPath("users.json");
        File file=new File(filePath);
        if(!file.exists()){
            file.createNewFile();
        }

 */



